version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '5000'
    ports:
      - '5000:5001'
    command: yarn run dev
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
